# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "400c31348d1161d918066fa2a8a0e2b0"
name = "shipping-calculator"
handle = "shipping-calculator-27"
application_url = "https://ribbon-breathing-foam-assess.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ribbon-breathing-foam-assess.trycloudflare.com/auth/callback",
  "https://ribbon-breathing-foam-assess.trycloudflare.com/auth/shopify/callback",
  "https://ribbon-breathing-foam-assess.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "appshipping-pinheiro.myshopify.com"
automatically_update_urls_on_dev = true
